schema {
    query: Query
    mutation: Mutation
}

type Query {
    getAuthors: [String]
    getAuthorsByName(name: String):[String]
    getBooks: [Book]
    getName: String
    getFavFoods: [String]
    addThis(a: Int, b: Int): Int
}

type Mutation {
    addBook(book: BookIn): Book
}

type Book {
    id: ID
    title: String
    year: Int
    author: String
    isbn: String
}

input BookIn {
    title: String
    year: Int
    author: String
    isbn: String
}